export const endpoints = {
    login: "user/login",
    register: "user/register",
    verifyOtp: "user/verify_otp",
    resentOtp: "user/resend_otp",
    forgotPassword: "user/forgot_password",
    resetPassword: "user/reset_password",
    getuserProfile: "user/get_profile",
    updateUserProfile: "user/update_profile",
    changeUserPassword: "user/change_password",
    userLogout: "user/logout",
    specialization: "specialization/get_list",
    therapistRegister: "therapist/register",
    therapistverify_otp: "therapist/verify_otp",
    therapistresend_otp: "therapist/resend_otp",
    therapistforgot_password: "therapist/forgot_password",
    therapistreset_password: "therapist/reset_password",
    therapistlogin: "therapist/login",
    therapistlogout: "therapist/logout",
    therapistget_profile: "therapist/get_profile",
    therapistupdate_profile: "therapist/update_profile",
    therapistchange_password: "therapist/change_password",
    useradd_card: "user/add_card",
    user_get_saved_cards: "user/get_saved_cards",
    user_set_as_default: "user/set_as_default",
    user_delete_particular_card: "user/delete_particular_card",
    terms_and_condition: "common/terms_and_condition",
    privacy_policy: "common/privacy_policy",
    update_avaiability: "therapist/update_avaiability",
    get_my_avaiability: "therapist/get_my_avaiability",
    search_nearby_therapist: "appointment/search_nearby_therapist",
    get_current_appointment: "therapist/get_current_appointment",
    user_current_appointment: "user/get_current_appointment",
    therapist_accept_call_request: "therapist/accept_call_request",
    user_complete_appointment_call: "user/complete_appointment_call",
    therapist_complete_appointment_call: "therapist/complete_appointment_call",
    therapist_get_past_appointments: "therapist/get_past_appointments",
    user_get_past_appointments: "user/get_past_appointments",
    user_give_appointment_feedback: "user/give_appointment_feedback",
    therapist_reject_call_request: "therapist/reject_call_request",
    user_cancel_call_appointment: "user/cancel_call_appointment",
    user_get_therapist_detail: "user/get_therapist_detail",
    common_contact_us: "common/contact_us",
    therapist_get_current_appointment: "therapist/get_current_appointment",
    user_get_current_appointment: "user/get_current_appointment",
    user_get_therapist_slot: "user/get_therapist_slot",
    schedule_appointment: "appointment/schedule_appointment",
    user_get_upcoming_appointments: "user/get_upcoming_appointments",
    therapist_get_upcoming_appointments: "therapist/get_upcoming_appointments",
    user_cancel_call_appointment: "user/cancel_upcoming_appointment",
    therapist_cancel_call_appointment: "therapist/cancel_upcoming_appointment",
    therapist_update_online_status: "therapist/update_online_status",
    therapist_get_Myfeedback: "therapist/get_my_feedbacks",
    user_get_calander_appointment: "user/get_calander_appointment",
    get_calander_appointment: "therapist/get_calander_appointment",
    get_therapist_notification_list:"therapist/get_notification_list",
    get_user_notification_list:"user/get_notification_list"



}
