const AppRoutes = {
    AuthStack: "AuthStack",
    DrawerStack: "DrawerStack",
    NonAuthStack: "NonAuthStack",
    Appointments: "Appointments",
    Splash: "Splash",
    Welcome: "Welcome",
    Home: "Home",
    Walkthrough: "Walkthrough",
    PrivacyPolicy: "PrivacyPolicy",
    ChooseLang: "ChooseLang",
    Login: 'Login',
    SignUp: 'SignUp',
    TermsCondition: "TermsCondition",
    Feedback: "Feedback",
    Notifications: "Notifications",
    Therapist: "Therapist",
    ContactUs: "ContactUs",
    BookTherapist: "BookTherapist",
    SelectTimeAndDate: "SelectTimeAndDate",
    SelectCategories: "SelectCategories",
    ForgotPwd: "ForgotPwd",
    Verification: "Verification",
    ResetPwd: "ResetPwd",
    Profile: "Profile",
    EditProfile: "EditProfile",
    TherapistProfile: "TherapistProfile",
    TherapistEditProfile: "TherapistEditProfile",
    ChatScreen: "ChatScreen",
    AddCard: "AddCard",
    Availability: "Availability",
    Video: "Video",
    IncomingCall: "IncomingCall",
    ChangePassword:"ChangePassword",
    SavedCard:"SavedCard",
    Bimetric:"Bimetric",
    BiometricVerification:"BiometricVerification",
    Setting:"Setting",
    Calender:"Calender"
}

export default AppRoutes